import { Grid, Paper, Table, TableBody, TableCell, TableContainer, TableHead, TableRow } from "@mui/material";
import dynamic from "next/dynamic";
import Head from "next/head";


const DymanicMap = dynamic(() => import("../components/map/Mapp"), {
  ssr: false,
});

export default function Home() {

  return (
    <>
      <Head>
        <title>Bike POints App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <DymanicMap /> 
      </main>
    </>
  );
}
